on:
  pull_request:
    paths:
      - pkg/**
      - internal/**
      - go.mod
      - go.sum
      - .github/worflows/go.yml
  push:
    branches:
      - main
    paths:
      - pkg/**
      - internal/**
      - go.mod
      - go.sum
      - .github/worflows/go.yml
name: Test
jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
    - uses: actions/checkout@v2
    - name: Format
      run: go fmt ./...
    - name: Build
      run: go build ./...
    - name: Vet
      run: go vet ./...
    - name: Test
      run: go test ./...
